### ISSUE TITLE
Today - "View All" and "Go To Read" links not working smoothly

### ISSUE THREAD

**Issue by wirelessed** [22media/JPMobilePM#30]
seems to go to another page before going to store or read page

**Comment by leejunkit** [comment]
Technical: this happens because the Today screen and the Store/Read screen are different React Native apps, so there is no way to smoothly segue to the new page. 

But we can prevent this if we "host" the "view all" and "read/devo" screens in the Today react native app. I think for purposes of the UX we should do this.
